image: samuelbarata/ssof:latest

stages:
  - Analyse

variables:
  LOG_LEVEL: DEBUG
  TOOL_NAME: py_analyser.py

Specification Slices:
  stage: Analyse
  before_script:
    - git clone https://gitlab-ci-token:${GITLAB_TOKEN}@${CI_SERVER_HOST}/ssof2324/project/Specification
  variables:
    SLICES_FOLDER: Specification/slices
    OUTPUT_FOLDER: output
    LOGS_FOLDER: logs
  script:
    - mkdir -p $LOGS_FOLDER
    - mkdir -p $OUTPUT_FOLDER
    - |
      for file in $SLICES_FOLDER/*.py; do
        slice_file=$(basename -- "$file")
        base_name_no_extension="${slice_file%.py}"
        patterns_file="${base_name_no_extension}.patterns.json"
        log_file="${base_name_no_extension}.log"
        echo "Slices folder: $SLICES_FOLDER"
        echo "Slice: $slice_file"
        echo "Patterns: $patterns_file"
        python3 $TOOL_NAME "$SLICES_FOLDER/${slice_file}" "$SLICES_FOLDER/${patterns_file}" --log-level $LOG_LEVEL --log-file $LOGS_FOLDER/$log_file --output-folder $OUTPUT_FOLDER
      done
  artifacts:
    paths:
      - $OUTPUT_FOLDER
      - $LOGS_FOLDER
    expire_in: 1 week
