image: samuelbarata/ssof:latest

stages:
  - Analyse

variables:
  LOG_LEVEL: DEBUG
  TOOL_NAME: py_analyser.py

Specification Slices:
  stage: Analyse
  before_script:
    - git clone https://gitlab-ci-token:${GITLAB_TOKEN}@${CI_SERVER_HOST}/ssof2324/project/Specification
  variables:
    SLICES_FOLDER: Specification/slices
    OUTPUT_FOLDER: output
    LOG_FILE: analyser.log
  script:
    - for file in $SLICES_FOLDER/*.py; do
        base_name=$(basename -- "$file")
        base_name_no_extension="${base_name%.py}"
        patterns_file="${base_name_no_extension}.patterns.json"
        python3 $TOOL_NAME "$SLICES_FOLDER/${file}" "$SLICES_FOLDER/${patterns_file}" --log-level $LOG_LEVEL --log-file $LOG_FILE --output-folder $OUTPUT_FOLDER
      done
  artifacts:
    paths:
      - $OUTPUT_FOLDER
      - $LOG_FILE
    expire_in: 1 week
